  name: Sync to Hugging Face Space

  on:
    push:
      branches:
        - main

  jobs:
    sync:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3

        - name: Set up Git
          run: git config --global user.name 'Cqcretador' && git config --global user.email 'cqcretador@gmail.com'

        - name: Add Hugging Face remote
          run: git remote add hf https://huggingface.co/spaces/Cqcretador/ia

        - name: Push to Hugging Face
          run: git push hf main
          env:
            HF_TOKEN: ${{ secrets.HF_TOKEN }}
